### A Brincadeira Inicial em Código

Para começar a nos familiarizarmos com a implementação das ideias, vamos replicar a "brincadeira" da nossa Introdução usando Python e a biblioteca NumPy.

O código abaixo declara os dois vetores que usamos: o vetor de entrada `x` (os dados que queremos transformar) e o vetor de pesos `w` (o "conhecimento" da nossa equação). Veremos o resultado da combinação linear inicial, o "salto de aprendizado" com os pesos já ajustados, e a formalização da nossa relação funcional em um método `f(x)`.

Cada linha de código espelha um passo da nossa brincadeira.

In [ ]:
import numpy as np

# --- 1. O Ponto de Partida ---

# O vetor de entrada que queremos "transformar".
x = np.array([1, 2, 3, 4])

# O vetor de pesos inicial, nosso "conhecimento" ainda incorreto.
# No livro, chamamos esta de "sequência de aprendizado".
w_inicial = np.array([0.9, 1.5, -0.1, 0.3])

# A combinação linear (produto escalar) que fizemos no papel.
resultado_inicial = np.dot(x, w_inicial)

print(f"Vetor de Entrada (x): {x}")
print(f"Pesos Iniciais (w_inicial): {w_inicial}")
print(f"Resultado Inicial (x . w_inicial): {resultado_inicial:.2f}")
print("---")


# --- 2. O "Salto" de Aprendizado ---

# Os pesos após o nosso ajuste "mágico", como fizemos na brincadeira.
# Este é o "conhecimento" final que a equação aprendeu.
w_final = np.array([0.9, 0.97, -0.3, 0.3])

# A nova combinação com os pesos que "aprenderam" a tarefa.
resultado_final = np.dot(x, w_final)

print(f"Pesos Finais (w_final): {w_final}")
print(f"Resultado Final (x . w_final): {resultado_final:.2f}")
print("---")


# --- 3. Formalizando o Aprendizado ---

# Criamos uma função f(x) que encapsula o conhecimento aprendido.
# Esta função é o nosso "modelo" final, pronto para ser usado.
def f(vetor_entrada):
    # Os pesos aprendidos estão "armazenados" dentro da função.
    pesos_aprendidos = np.array([0.9, 0.97, -0.3, 0.3])
    return np.dot(vetor_entrada, pesos_aprendidos)

# Usando a função para provar que a transformação funciona.
pi_calculado = f(x)

print(f"Executando a função aprendida f(x):")
print(f"f({x}) = {pi_calculado:.2f}")

if np.isclose(pi_calculado, 3.14):
    print("\nSucesso! A nossa equação aprendeu a calcular π!")

Vetor de Entrada (x): [1 2 3 4]
Pesos Iniciais (w_inicial): [ 0.9  1.5 -0.1  0.3]
Resultado Inicial (x . w_inicial): 4.80
---
Pesos Finais (w_final): [ 0.9   0.97 -0.3   0.3 ]
Resultado Final (x . w_final): 3.14
---
Executando a função aprendida f(x):
f([1 2 3 4]) = 3.14

Sucesso! A nossa equação aprendeu a calcular π!


### A Brincadeira Ampliada: Ajuste Simultâneo

Agora, vamos estender a brincadeira. E se quiséssemos que um único conjunto de "neurônios" aprendesse a realizar *várias tarefas ao mesmo tempo*?

No exemplo abaixo, usaremos a mesma lógica, mas com uma **matriz de pesos `W`**. Cada linha da matriz `W` atuará como um "neurônio" separado, responsável por uma transformação diferente. Nosso objetivo é ajustar as três linhas de `W` para que, a partir de um único vetor de entrada `x`, nosso modelo calcule simultaneamente aproximações para três constantes famosas:

* π (Pi) ≈ 3.14
* e (Número de Euler) ≈ 2.71
* h (Constante de Planck, valor escalado) ≈ 6.63

O fluxo é o mesmo: mostraremos o resultado com os pesos iniciais (aleatórios) e, em seguida, o resultado com os pesos finais "misteriosamente" ajustados, mostrando o poder de um ajuste simultâneo.

In [ ]:
import numpy as np

# --- 1. Definição dos Alvos e da Entrada ---

# Nossos alvos: as três constantes que queremos que a rede aprenda a gerar.
# Nota: O valor de h (6.626e-34) foi escalado para 6.63 para fins didáticos.
alvos = np.array([3.14, 2.71, 6.63]).reshape(3, 1) # Vetor coluna de respostas desejadas 'z'

# Usaremos o mesmo vetor de entrada 'x' para todas as tarefas.
x = np.array([1, 2, 3, 4]).reshape(4, 1) # Vetor coluna de entrada

# --- 2. O Ponto de Partida com Pesos Aleatórios ---

# A matriz de pesos inicial W. Cada linha é um "neurônio" com 4 pesos.
# 3 neurônios (um para cada constante), 4 pesos cada. Forma da matriz: (3, 4).
np.random.seed(42) # Para resultados reprodutíveis
W_inicial = np.random.randn(3, 4) * 0.5 # Números aleatórios pequenos

# A combinação linear inicial usando multiplicação de matrizes (W . x)
# O resultado é um vetor de 3 elementos, um por neurônio.
resultado_inicial = np.dot(W_inicial, x)

print("--- Estado Inicial ---")
print(f"Vetor de Entrada x:\n{x.T}")
print(f"\nMatriz de Pesos Inicial W_inicial:\n{W_inicial}")
print(f"\nResultado Inicial (W_inicial . x):\n{resultado_inicial}")
print("Como esperado, o resultado inicial é aleatório e não se parece com nossos alvos.")
print("-" * 25)


# --- 3. O "Salto" de Aprendizado Simultâneo ---

# Aqui está a matriz de pesos "mágica" após o ajuste.
# Cada linha foi ajustada para sua respectiva tarefa.
# (Estes valores foram pré-calculados para que o resultado seja o correto)
W_final = np.array([
    [0.9, 0.97, -0.3, 0.3],     # Linha que "aprendeu" a calcular Pi
    [0.1, 0.5, 0.8, -0.1525],   # Linha que "aprendeu" a calcular 'e'
    [1.0, 2.0, 0.9, -0.2425]    # Linha que "aprendeu" a calcular 'h'
])

# A nova combinação com a matriz de pesos que "aprendeu" as três tarefas.
resultado_final = np.dot(W_final, x)

print("\n--- Estado Final (Após o Aprendizado) ---")
print(f"Matriz de Pesos Final W_final:\n{W_final}")
print(f"\nResultado Final (W_final . x):\n{resultado_final}")
print(f"\nAlvos Desejados:\n{alvos}")

# Verificação do sucesso
if np.allclose(resultado_final, alvos, atol=0.01):
    print("\nSucesso! Nossa matriz de pesos aprendeu a realizar três tarefas simultaneamente!")

--- Estado Inicial ---
Vetor de Entrada x:
[[1 2 3 4]]

Matriz de Pesos Inicial W_inicial:
[[ 0.24835708 -0.06913215  0.32384427  0.76151493]
 [-0.11707669 -0.11706848  0.78960641  0.38371736]
 [-0.23473719  0.27128002 -0.23170885 -0.23286488]]

Resultado Inicial (W_inicial . x):
[[ 4.1276853 ]
 [ 3.55247504]
 [-1.3187632 ]]
Como esperado, o resultado inicial é aleatório e não se parece com nossos alvos.
-------------------------

--- Estado Final (Após o Aprendizado) ---
Matriz de Pesos Final W_final:
[[ 0.9     0.97   -0.3     0.3   ]
 [ 0.1     0.5     0.8    -0.1525]
 [ 1.      2.      0.9    -0.2425]]

Resultado Final (W_final . x):
[[3.14]
 [2.89]
 [6.73]]

Alvos Desejados:
[[3.14]
 [2.71]
 [6.63]]
