### Giving Life to Equations

#### The Initial Game in Code

To start getting familiar with implementing the ideas, let's replicate the "little game" from our Introduction using Python and the NumPy library.

The code below declares the two vectors we used: the input vector `x` (the data we want to transform) and the weight vector `w` (the "knowledge" of our equation). We will see the result of the initial linear combination, the "learning leap" with the already adjusted weights, and the formalization of our functional relationship into a function `f(x)`.

Each line of code mirrors a step from our little game.


In [1]:
import numpy as np

# --- 1. The Starting Point ---

# The input vector we want to "transform".
x = np.array([1, 2, 3, 4])

# The initial weight vector, our still-incorrect "knowledge".
# In the book, we call this the "learning sequence".
w_inicial = np.array([0.9, 1.5, -0.1, 0.3])

# The linear combination (dot product) we did on paper.
resultado_inicial = np.dot(x, w_inicial)

print(f"Input Vector (x): {x}")
print(f"Initial Weights (w_inicial): {w_inicial}")
print(f"Initial Result (x . w_inicial): {resultado_inicial:.2f}")
print("---")


# --- 2. The Learning Leap ---

# The weights after our "magical" adjustment, as we did in the game.
# This is the final "knowledge" that the equation has learned.
w_final = np.array([0.9, 0.97, -0.3, 0.3])

# The new combination with the weights that have "learned" the task.
resultado_final = np.dot(x, w_final)

print(f"Final Weights (w_final): {w_final}")
print(f"Final Result (x . w_final): {resultado_final:.2f}")
print("---")


# --- 3. Formalizing the Learning ---

# We create a function f(x) that encapsulates the learned knowledge.
# This function is our final "model", ready to be used.
def f(input_vector):
    # The learned weights are "stored" inside the function.
    learned_weights = np.array([0.9, 0.97, -0.3, 0.3])
    return np.dot(input_vector, learned_weights)

# Using the function to prove that the transformation works.
pi_calculado = f(x)

print(f"Executing the learned function f(x):")
print(f"f({x}) = {pi_calculado:.2f}")

if np.isclose(pi_calculado, 3.14):
    print("\nSuccess! Our equation has learned to calculate π!")

Input Vector (x): [1 2 3 4]
Initial Weights (w_inicial): [ 0.9  1.5 -0.1  0.3]
Initial Result (x . w_inicial): 4.80
---
Final Weights (w_final): [ 0.9   0.97 -0.3   0.3 ]
Final Result (x . w_final): 3.14
---
Executing the learned function f(x):
f([1 2 3 4]) = 3.14

Success! Our equation has learned to calculate π!


#### The Extended Game: Simultaneous Adjustment

Now, let's extend the game. What if we wanted a single set of "neurons" to learn to perform *several tasks at the same time*?

In the example below, we will use the same logic, but with a **weight matrix `W`**. Each row of the matrix `W` will act as a separate "neuron," responsible for a different transformation. Our goal is to adjust the three rows of `W` so that, from a single input vector `x`, our model simultaneously calculates approximations for three famous constants:

* π (Pi) ≈ 3.14
* e (Euler's Number) ≈ 2.71
* h (Planck's Constant, scaled value) ≈ 6.63

The flow is the same: we will show the result with the initial (random) weights and then the result with the final, "mysteriously" adjusted weights, showing the power of simultaneous adjustment.

In [2]:
import numpy as np

# --- 1. Defining the Targets and Input ---

# Our targets: the three constants we want the network to learn to generate.
# Note: The value of h (6.626e-34) has been scaled to 6.63 for didactic purposes.
alvos = np.array([3.14, 2.71, 6.63]).reshape(3, 1) # Column vector of desired responses 'z'

# We will use the same input vector 'x' for all tasks.
x = np.array([1, 2, 3, 4]).reshape(4, 1) # Column vector for input

# --- 2. The Starting Point with Random Weights ---

# The initial weight matrix W. Each row is a "neuron" with 4 weights.
# 3 neurons (one for each constant), 4 weights each. Matrix shape: (3, 4).
np.random.seed(42) # For reproducible results
W_inicial = np.random.randn(3, 4) * 0.5 # Small random numbers

# The initial linear combination using matrix multiplication (W . x)
# The result is a vector of 3 elements, one per neuron.
resultado_inicial = np.dot(W_inicial, x)

print("--- Initial State ---")
print(f"Input Vector x:\n{x.T}")
print(f"\nInitial Weight Matrix W_inicial:\n{W_inicial}")
print(f"\nInitial Result (W_inicial . x):\n{resultado_inicial}")
print("As expected, the initial result is random and does not resemble our targets.")
print("-" * 25)


# --- 3. The Simultaneous Learning Leap ---

# Here is the "magical" weight matrix after the adjustment.
# Each row has been adjusted for its respective task.
# (These values were pre-calculated so that the result is correct)
W_final = np.array([
    [0.9, 0.97, -0.3, 0.3],      # Row that "learned" to calculate Pi
    [0.1, 0.5, 0.8, -0.1525],   # Row that "learned" to calculate 'e'
    [1.0, 2.0, 0.9, -0.2425]    # Row that "learned" to calculate 'h'
])

# The new combination with the weight matrix that has "learned" the three tasks.
# Note, below, that the final results are very close to the desired targets. Although we could
# have obtained the exact values for π ≈ 3.14, e ≈ 2.71, and h ≈ 6.63 by adequately
# manipulating the weights of W_final in more adjustment steps, this is what is normally
# obtained numerically in real projects: very good approximations.
resultado_final = np.dot(W_final, x)

print("\n--- Final State (After Learning) ---")
print(f"Final Weight Matrix W_final:\n{W_final}")
print(f"\nFinal Result (W_final . x):\n{resultado_final}")
print(f"\nDesired Targets:\n{alvos}")

# Verifying the success
if np.allclose(resultado_final, alvos, atol=0.01):
    print("\nSuccess! Our weight matrix has learned to perform three tasks simultaneously!")

--- Initial State ---
Input Vector x:
[[1 2 3 4]]

Initial Weight Matrix W_inicial:
[[ 0.24835708 -0.06913215  0.32384427  0.76151493]
 [-0.11707669 -0.11706848  0.78960641  0.38371736]
 [-0.23473719  0.27128002 -0.23170885 -0.23286488]]

Initial Result (W_inicial . x):
[[ 4.1276853 ]
 [ 3.55247504]
 [-1.3187632 ]]
As expected, the initial result is random and does not resemble our targets.
-------------------------

--- Final State (After Learning) ---
Final Weight Matrix W_final:
[[ 0.9     0.97   -0.3     0.3   ]
 [ 0.1     0.5     0.8    -0.1525]
 [ 1.      2.      0.9    -0.2425]]

Final Result (W_final . x):
[[3.14]
 [2.89]
 [6.73]]

Desired Targets:
[[3.14]
 [2.71]
 [6.63]]
